version: "3"
services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3009:3306

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - ./vendor/bundle:/rails/vendor/bundle # bundler のキャッシュを共有
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - "3008:3000"
    depends_on:
      - db
    tty: true # デバッグのためにTTYを有効化
    stdin_open: true # デバッグセッションのために標準入力を開く

volumes:
  mysql-data:
