version: "3.9"

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # 必要なら MYSQL_USER / MYSQL_PASSWORD も .env で定義して使ってください
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - mysql-data:/var/lib/mysql
    # 外部からMySQLに接続したい場合のみ公開
    ports:
      - "${MYSQL_PORT_ON_HOST:-3009}:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    # 外部からRedisを触らないならポート公開は不要（必要ならコメント解除）
    # ports:
    #   - "${REDIS_PORT_ON_HOST:-6370}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: .
      dockerfile: Dockerfile
    user: "0:0"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p ${RAILS_PORT:-3000} -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    environment:
      TZ: ${TZ}
      RAILS_ENV: ${RAILS_ENV}
      # DBは database.yml で host: db, username/password を参照にする想定
      # もしくは DATABASE_URL を使う場合はこちらを利用:
      # DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SIDEKIQ_REDIS_URL: ${SIDEKIQ_REDIS_URL}
      # オンラインクラス API 認証＆先頭URL
      ONLINE_CLASS_API_BASE: ${ONLINE_CLASS_API_BASE}
      ONLINE_CLASS_LOGIN_PATH: ${ONLINE_CLASS_LOGIN_PATH}
      ONLINE_CLASS_EMAIL: ${ONLINE_CLASS_EMAIL}
      ONLINE_CLASS_PASSWORD: ${ONLINE_CLASS_PASSWORD}
      # LINE Bot
      LINE_CHANNEL_SECRET: ${LINE_CHANNEL_SECRET}
      LINE_CHANNEL_ACCESS_TOKEN: ${LINE_CHANNEL_ACCESS_TOKEN}
      LINE_PUSH_TO: ${LINE_PUSH_TO}
    ports:
      - "${API_PORT_ON_HOST:-3008}:${RAILS_PORT:-3000}"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    tty: true
    stdin_open: true

  sidekiq:
    build:
      context: .
    user: "0:0"
    command: bash -c "bundle exec sidekiq"
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    environment:
      TZ: ${TZ}
      RAILS_ENV: ${RAILS_ENV}
      REDIS_URL: ${REDIS_URL}
      SIDEKIQ_REDIS_URL: ${SIDEKIQ_REDIS_URL}
      ONLINE_CLASS_API_BASE: ${ONLINE_CLASS_API_BASE}
      ONLINE_CLASS_LOGIN_PATH: ${ONLINE_CLASS_LOGIN_PATH}
      ONLINE_CLASS_EMAIL: ${ONLINE_CLASS_EMAIL}
      ONLINE_CLASS_PASSWORD: ${ONLINE_CLASS_PASSWORD}
      LINE_CHANNEL_SECRET: ${LINE_CHANNEL_SECRET}
      LINE_CHANNEL_ACCESS_TOKEN: ${LINE_CHANNEL_ACCESS_TOKEN}
      LINE_PUSH_TO: ${LINE_PUSH_TO}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  mysql-data:
  bundle:
  redis_data:
