# config/scheduler_development.yml
onclass_mentions_every:
  class: "OnclassMentionsWorker"
  cron: "0 7-23/2 * * *"   # 07,09,11,13,15,17,19,21,23
  queue: onclass_comunity_Mentions
  tz: "Asia/Tokyo"
  description: "コミュニティメンション機能通知(7~23時に実行)"

onclass_pdca_every_2h:
  class: "OnclassPdcasStudentsWorker"
  cron: "0 7-23/2 * * *"   # 07,09,11,13,15,17,19,21,23
  queue: onclass_comunity_PdcasStudents
  tz: "Asia/Tokyo"
  description: "コミュニティ機能毎日のPDCA通知(7~23時に実行)"