# config/scheduler_development.yml
onclass_mentions_every:
  class: "OnclassMentionsWorker"
  cron: "0 7-24/30 * * * *"   # 30分おきに実行
  queue: onclass_comunity_Mentions
  tz: "Asia/Tokyo"
  description: "コミュニティメンション機能通知(30分おきに実行)"

onclass_pdca_every:
  class: "OnclassPdcaStudentsWorker"
  cron: "0 7-23/2 * * *"   # 07,09,11,13,15,17,19,21,23
  queue: onclass_comunity_pdca_students
  tz: "Asia/Tokyo"
  description: "コミュニティ機能毎日のPDCA通知(7~23時に2時間おきに実行)"

onclass_students_data:
  class: "OnclassStudentsDataWorker"
  cron: "0 7-23/2 * * *"   # 07,09,11,13,15,17,19,21,23
  queue: onclass_students_data
  tz: "Asia/Tokyo"
  description: "オンクラス受講生データ同期"


lme_line_inflows_daily:
  cron: "0 7-23/2 * * *"   # 07,09,11,13,15,17,19,21,23
  class: "LmeLineInflowsWorker"
  queue: lme_line_inflows
  description: "LME inflows: run 1 day per execution (JST)."