# config/scheduler_development.yml
# onclass_mentions_every:
#   class: "Onclass::MentionsWorker"
#   cron: "0,30 7-23 * * *"   # 7-23時の間で30分おきに実行
#   queue: onclass_comunity_Mentions
#   tz: "Asia/Tokyo"
#   description: "コミュニティメンション機能通知(7-23時の間で30分おきに実行)"

# onclass_pdca_every:
#   class: "Onclass::PdcaStudentsWorker"
#   cron: "0 7-23/2 * * *"   # 07,09,11,13,15,17,19,21,23
#   queue: onclass_comunity_pdca_students
#   tz: "Asia/Tokyo"
#   description: "コミュニティ機能毎日のPDCA通知(7~23時に2時間おきに実行)"

onclass_students_front:
  class: "Onclass::StudentsDataWorker"
  cron: "0 */2 * * *"      # 2時間毎など
  queue: onclass_students_data
  args:
    - "oYTO4UDI6MGb"
    - "フロントコース受講生"
  tz: "Asia/Tokyo"
  description: "フロントコース受講生データ取得(2時間毎)"

onclass_students_backend:
  class: "Onclass::StudentsDataWorker"
  cron: "15 */2 * * *"     # 2時間毎 + 15分（ずらす）
  queue: onclass_students_data
  args:
    - "oEDI6MGb"
    - "フリーエンジニア養成コース"
  tz: "Asia/Tokyo"
  description: "バックエンドコース受講生データ取得(2時間毎)"

lme_line_inflows_daily:
  class: "Lme::LineInflowsWorker"
  cron: "0 7-23/2 * * *"   # 07,09,11,13,15,17,19,21,23
  queue: lme_line_inflows
  args:
    - "2023-01-01"
  tz: "Asia/Tokyo"
  description: "LME LINE流入数集計(2時間おき)"

# ★ 追加（ダッシュボード集計）
lme_line_counts_every:
  class: "Lme::LineCountsWorker"
  cron: "5 7-23/2 * * *"   # 流入集計の5分後に実行
  queue: lme_line_counts
  tz: "Asia/Tokyo"
  description: "LME LINEダッシュボード更新(2時間おき)"
